project:
  type: website

website:
  title: "benchmarkdown"
  navbar:
    right:
      - text: Home
        href: index.qmd
      - text: Blog
        href: blog.qmd
      - text: Talks
        href: talks.qmd
      - icon: github
        href: https://github.com/KittJonathan
      - icon: linkedin
        href: https://www.linkedin.com/in/jonathan-kitt/
format:
  html:
    theme:
      - lux
    css: styles.css

editor: visual

